### ISSUE TITLE
Function chaining format

### ISSUE THREAD

**Issue by SamuFinnos** [Barteling/STweep#33] opened 2021-03-16 07:11 UTC
I have a function that uses method chaining to create a message. The formatter does not format it nicely
Before format:
```
testLog.addString('TestLog1').LogType(LogTypeEnum.Default).Send();
```

After format:
```
testLog.addString(
'TestLog4'
).LogType(
LogTypeEnum.Message
).Send();
```
This would be the preferred option:
```
testLog
 .addString('TestLog1')
 .LogType(LogTypeEnum.Default)
 .Send();
```

**Comment by Barteling** [comment] 2021-03-16 08:02
@SamuFinnos , Thank for reporting, I agree this has to be improved.
I'll pick it up.  
I will close this issue because it's a duplicate of #10 I'll report progress in there.

**Closed as completed by Barteling** 2021-03-16 08:02 UTC
Labels: Type: Enhancement

**Comment by Barteling** [comment] 2021-03-26 08:14
@SamuFinnos 

I  improved formatting of fluent interfaces in STweep for TwinCAT beta 3.3.0 and Stweep for Codesys 3.3.0

https://www.stweep.com/codesys-beta-releases/
https://www.stweep.com/releases/
