### ISSUE TITLE
Warning when opening Visual Studio after upgrading to 1.0.6

### ISSUE THREAD

**Issue by Roald87** [Barteling/STweep#11] opened 2021-01-13 08:57 UTC
I just upgraded to v1.0.6 from 1.0.5. When I opened visual studio for the first time I got this error:

![error](https://user-images.githubusercontent.com/20192767/104428581-ef135e00-5584-11eb-8d1e-986d82bb8e1b.PNG)
Full error from ActivityLog: [error.txt](https://github.com/Barteling/STweep/files/5807475/error.txt)

I then closed visual studio and got the following error:

![error_on_close](https://user-images.githubusercontent.com/20192767/104428906-50d3c800-5585-11eb-9060-c0e2d72bd9bc.PNG)

After restarting VS 15.9.29 the errors were gone, even though I selected "Yes" in both windows. So far STweep seems to work normally and the *About* menu shows that version 1.0.6 is installed.

I did not have any issues when I upgraded last time from v1.0.2 (I think or maybe it was 1.0.0 or 1.0.1) to v1.0.5.

**Comment by Barteling** [comment] 2021-01-13 12:58
I'm not sure what to do with this. 
I cannot reproduce it, and STweep has nothing to do with TcOpcUaSrv.VSIX

The activity log mentions that a file is in use by another process, perhaps a visual studio bug? 
Since STweep is working, i'll close this issue for now but if it happens again after a STweep installation let me know.

**Closed by Barteling** 2021-01-13 12:58 UTC
Labels: Type: Bug

**Comment by Roald87** [comment] 2021-01-13 14:01
No problem. Wanted to report it just in case you get another report.
